/*
 * ADP APIs
 * ADP API endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PayrollApi
 */
@Disabled
public class PayrollApiTest {

    private static PayrollApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PayrollApi(apiClient);
    }

    /**
     * Payroll Outputs V1 (List for Region / Company Code / Year / Week)
     *
     * Fetches a list of payroll outputs given a Region Code, Company Code, Year and Week.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listPayrollOutputsTest() throws ApiException {
        String $filter = null;
        String $count = null;
        String useCache = null;
        String level = null;
        String $select = null;
        api.listPayrollOutputs()
                .$filter($filter)
                .$count($count)
                .useCache(useCache)
                .level(level)
                .$select($select)
                .execute();
        // TODO: test validations
    }

}
