/*
 * ADP APIs
 * ADP API endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TokenRequestApi
 */
@Disabled
public class TokenRequestApiTest {

    private static TokenRequestApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TokenRequestApi(apiClient);
    }

    /**
     * Token Request (Authorization Header)
     *
     * A request to get an OAuth bearer token for our demo ADP Workforce Now by adding an Authorization header containing the base-64 encoded credentials.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createWithAuthorizationHeaderTest() throws ApiException {
        String grantType = null;
        String clientId = null;
        String clientSecret = null;
        api.createWithAuthorizationHeader()
                .grantType(grantType)
                .clientId(clientId)
                .clientSecret(clientSecret)
                .execute();
        // TODO: test validations
    }

}
