/*
 * ADP APIs
 * ADP API endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class PayrollApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PayrollApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public PayrollApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call listPayrollOutputsCall(String $filter, String $count, String useCache, String level, String $select, Object body, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/payroll/v1/payroll-output";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if ($filter != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$filter", $filter));
        }

        if ($count != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$count", $count));
        }

        if (useCache != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("use-cache", useCache));
        }

        if (level != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("level", level));
        }

        if ($select != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("$select", $select));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/octet-stream"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listPayrollOutputsValidateBeforeCall(String $filter, String $count, String useCache, String level, String $select, Object body, final ApiCallback _callback) throws ApiException {
        return listPayrollOutputsCall($filter, $count, useCache, level, $select, body, _callback);

    }


    private ApiResponse<Void> listPayrollOutputsWithHttpInfo(String $filter, String $count, String useCache, String level, String $select, Object body) throws ApiException {
        okhttp3.Call localVarCall = listPayrollOutputsValidateBeforeCall($filter, $count, useCache, level, $select, body, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call listPayrollOutputsAsync(String $filter, String $count, String useCache, String level, String $select, Object body, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = listPayrollOutputsValidateBeforeCall($filter, $count, useCache, level, $select, body, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class ListPayrollOutputsRequestBuilder {
        private String $filter;
        private String $count;
        private String useCache;
        private String level;
        private String $select;
        private Object body;

        private ListPayrollOutputsRequestBuilder() {
        }

        /**
         * Set body
         * @param body  (optional)
         * @return ListPayrollOutputsRequestBuilder
         */
        public ListPayrollOutputsRequestBuilder body(Object body) {
            this.body = body;
            return this;
        }

        /**
         * Set $filter
         * @param $filter  (optional)
         * @return ListPayrollOutputsRequestBuilder
         */
        public ListPayrollOutputsRequestBuilder $filter(String $filter) {
            this.$filter = $filter;
            return this;
        }
        
        /**
         * Set $count
         * @param $count  (optional)
         * @return ListPayrollOutputsRequestBuilder
         */
        public ListPayrollOutputsRequestBuilder $count(String $count) {
            this.$count = $count;
            return this;
        }
        
        /**
         * Set useCache
         * @param useCache  (optional)
         * @return ListPayrollOutputsRequestBuilder
         */
        public ListPayrollOutputsRequestBuilder useCache(String useCache) {
            this.useCache = useCache;
            return this;
        }
        
        /**
         * Set level
         * @param level  (optional)
         * @return ListPayrollOutputsRequestBuilder
         */
        public ListPayrollOutputsRequestBuilder level(String level) {
            this.level = level;
            return this;
        }
        
        /**
         * Set $select
         * @param $select  (optional)
         * @return ListPayrollOutputsRequestBuilder
         */
        public ListPayrollOutputsRequestBuilder $select(String $select) {
            this.$select = $select;
            return this;
        }
        
        /**
         * Build call for listPayrollOutputs
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            Object body = buildBodyParams();
            return listPayrollOutputsCall($filter, $count, useCache, level, $select, body, _callback);
        }

        private Object buildBodyParams() {
            return this.body;
        }

        /**
         * Execute listPayrollOutputs request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            Object body = buildBodyParams();
            listPayrollOutputsWithHttpInfo($filter, $count, useCache, level, $select, body);
        }

        /**
         * Execute listPayrollOutputs request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            Object body = buildBodyParams();
            return listPayrollOutputsWithHttpInfo($filter, $count, useCache, level, $select, body);
        }

        /**
         * Execute listPayrollOutputs request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            Object body = buildBodyParams();
            return listPayrollOutputsAsync($filter, $count, useCache, level, $select, body, _callback);
        }
    }

    /**
     * Payroll Outputs V1 (List for Region / Company Code / Year / Week)
     * Fetches a list of payroll outputs given a Region Code, Company Code, Year and Week.
     * @return ListPayrollOutputsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public ListPayrollOutputsRequestBuilder listPayrollOutputs() throws IllegalArgumentException {
        return new ListPayrollOutputsRequestBuilder();
    }
}
